import sqlite3
import json
import os

db_path = "yt_automate.db"
out_path = r"C:\Users\Prana\.gemini\antigravity-ide\brain\e09ce35a-bd23-438a-a7d0-f5e15e129bc8\pipeline_results.md"

def fetch_all(cursor, query):
    cursor.execute(query)
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]

try:
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    topics = fetch_all(cursor, "SELECT t.*, s.total_score, s.novelty, s.audience_size, s.competition FROM topics t LEFT JOIN topic_scores s ON t.id = s.topic_id")
    contents = fetch_all(cursor, "SELECT * FROM content_packages")
    assets = fetch_all(cursor, "SELECT * FROM assets")
    asset_packages = fetch_all(cursor, "SELECT * FROM asset_packages")
    
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# E2E Pipeline Results\n\n")
        f.write("This artifact contains the full output generated by the End-to-End pipeline using `deepseek-ai/deepseek-v4-pro`.\n\n")
        
        f.write("## Phase 1: Research Engine (Topics)\n")
        if topics:
            for t in topics:
                f.write(f"### Topic: {t['title']}\n")
                f.write(f"- **Score**: {t['total_score']}\n")
                f.write(f"- **Novelty Score**: {t['novelty']}\n")
                f.write(f"- **Audience Size**: {t['audience_size']}\n")
                f.write(f"- **Competition**: {t['competition']}\n")
                f.write(f"> {t['description']}\n\n")
        else:
            f.write("No topics generated.\n\n")
            
        f.write("## Phase 2: Content Engine (Script & Strategy)\n")
        if contents:
            for c in contents:
                f.write(f"### Content Strategy\n")
                strat = json.loads(c['strategy_json']) if c['strategy_json'] else {}
                f.write(f"```json\n{json.dumps(strat, indent=2)}\n```\n\n")
                
                f.write(f"### Hook Used\n")
                f.write(f"> {c['hook_text']}\n\n")
                
                f.write(f"### Final Video Script\n")
                f.write(f"{c['final_script']}\n\n")
        else:
            f.write("No content generated.\n\n")
            
        f.write("## Phase 3: Asset Engine (Generated Media)\n")
        if assets:
            for a in assets:
                f.write(f"### Asset: {a['asset_type']}\n")
                f.write(f"- **Status**: {a['status']}\n")
                f.write(f"- **File Path**: `{a['file_path']}`\n")
                f.write(f"- **Prompt/Text**: {a['prompt']}\n\n")
        else:
            f.write("No assets generated.\n\n")
            
    print(f"Successfully wrote results to {out_path}")
except Exception as e:
    print(f"Error: {e}")
