from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
import json
import os

from database.models import Topic, TopicScore, ContentPackage, Script, ScriptRevision, Hook, Outline, Scene, Asset

db_path = "sqlite:///./yt_automate.db"
engine = create_engine(db_path)
Session = sessionmaker(bind=engine)
session = Session()

out_path = r"C:\Users\Prana\.gemini\antigravity-ide\brain\e09ce35a-bd23-438a-a7d0-f5e15e129bc8\pipeline_results.md"

try:
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# E2E Pipeline Results\n\n")
        f.write("This artifact contains the full output generated by the End-to-End pipeline using `deepseek-ai/deepseek-v4-pro`.\n\n")
        
        f.write("## Phase 1: Research Engine (Topics)\n")
        topics = session.query(Topic).all()
        if topics:
            for t in topics:
                f.write(f"### Topic: {t.title}\n")
                if t.score:
                    f.write(f"- **Score**: {t.score.total_score}\n")
                    f.write(f"- **Novelty Score**: {t.score.novelty}\n")
                    f.write(f"- **Audience Size**: {t.score.audience_size}\n")
                    f.write(f"- **Competition**: {t.score.competition}\n")
                f.write(f"> {t.description}\n\n")
        else:
            f.write("No topics generated.\n\n")
            
        f.write("## Phase 2: Content Engine (Script & Strategy)\n")
        packages = session.query(ContentPackage).all()
        if packages:
            for p in packages:
                f.write(f"### Content Package ({p.status})\n")
                
                hook = session.query(Hook).filter(Hook.package_id == p.id, Hook.is_selected == True).first()
                if hook:
                    f.write(f"#### Selected Hook\n")
                    f.write(f"> {hook.text}\n\n")
                
                outline = session.query(Outline).filter(Outline.package_id == p.id).first()
                if outline:
                    f.write(f"#### Outline Structure\n")
                    f.write(f"```json\n{json.dumps(outline.structure_json, indent=2)}\n```\n\n")
                
                script = session.query(Script).filter(Script.package_id == p.id).first()
                if script:
                    f.write(f"#### Final Video Script\n")
                    f.write(f"**Quality Scores**:\n")
                    f.write(f"- Fact Check: {script.fact_score}\n")
                    f.write(f"- Retention: {script.retention_score}\n")
                    f.write(f"- Overall Quality: {script.quality_score}\n\n")
                    
                    last_rev = session.query(ScriptRevision).filter(ScriptRevision.script_id == script.id).order_by(ScriptRevision.iteration.desc()).first()
                    if last_rev:
                        f.write(f"**Script Text**:\n")
                        f.write(f"> {last_rev.text}\n\n")
                
                scenes = session.query(Scene).filter(Scene.package_id == p.id).all()
                if scenes:
                    f.write(f"#### Scenes\n")
                    for s in scenes:
                        f.write(f"**Scene {s.scene_number}**:\n")
                        f.write(f"  - Narration: {s.narration_text}\n")
                        f.write(f"  - Visuals: {s.visual_description}\n")
                        f.write(f"  - Asset Type: {s.asset_type_required}\n")
                    f.write(f"\n")
        else:
            f.write("No content generated.\n\n")
            
        f.write("## Phase 3: Asset Engine (Generated Media)\n")
        assets = session.query(Asset).all()
        if assets:
            for a in assets:
                f.write(f"### Asset: {a.asset_type}\n")
                f.write(f"- **Provider**: {a.provider}\n")
                f.write(f"- **File Path**: `{a.file_path}`\n\n")
        else:
            f.write("No assets generated.\n\n")
            
    print(f"Successfully wrote results to {out_path}")
except Exception as e:
    import traceback
    traceback.print_exc()
